baseURL       = "https://customcarpentrysouthwest.co.uk"
languageCode  = "en-us"
title         = "Custom Carpentry | Carpentry Services in the South West"
theme         = "roxo-hugo"
summarylength = 25

[build]
publish = "public"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contact us"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/cc-logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Custom Carpentry | Carpentry Services in the South West"
  author = "Custom Carpentry"
  # Google Analitycs
  googleAnalitycsID = "G-M08TY5ZD3T"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/mlezdkql"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact us"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/background.jpeg"
    heading               = "We are a South West based Carpentry & Construction Company"
    tagline               = "We specialise in custom design and builds on a wide range of projects for your home, garden and business"
    primary_button        = "See Our Work"
    primary_button_url    = "portfolio"
    secondary_button      = "Contact us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORK"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = ""
      phone   = "+447818695032"
      email   = "mike@customcarpentrysouthwest.co.uk"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Custom Carpentry"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact us"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/customcarpentryuk"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/customcarpentry.sw"
      # Footer Service
      [params.footer.service]
        title       = "We help customers"
        description = "With a highly skilled team we always go the extra mile to give all clients 100% satisfaction on any projects undertaken. All aspects of carpentry from small domestic jobs to larger commercial work covered."